Repository globocom/husky-client, pull requests merged in 2018-12, with the labels that each got.

#25 [REFACT] Change gas into gosec
  analysis/output.go
  types/gosec.go
Labels: refact

#26 [FIX] Adjust output logic
  analysis/analysis.go
  analysis/output.go
  main.go
  types/types.go
Labels: bug, refact

#28 Brakeman parse and RetireJS parse
  analysis/output.go
  types/brakeman.go
  types/retirejs.go
Labels: feature
